# fly.toml app configuration file generated for routine-master on 2023-05-05T23:06:51-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "routine-master"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/project/public"
  url_prefix = "/"

[env]
  RAILS_ENV="production"
  APPLICATION_PORT="3000"

[build]
  dockerfile = "Dockerfile.fly"
